using System.Reflection;
using OpenQA.Selenium;

namespace NewTest.SeleniumExampleTest.Configurations;

public class DefaultWebDriverFactory
{
    private static string DriverPath => Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

    public DefaultWebDriverFactory(DriverPath driverPath,
        IWebDriverConfiguration configuration,
        IDriverOptionFactory driverOptionFactory = null) : this(driverPath.PathString,
        configuration.GridUri, driverOptionsFactory)
    {
    }

    public IWebDriver GetRemoteWebDriver(IWebDriverConfiguration configuration)
    {
        if (configuration.IsLocal)
        {
            throw new ArgumentException("A Local WebDriver Instance cannot be generated by this method");
        }

        return GetRemoteWebDriver(configuration.Browser, configuration.PlatformType, configuration.WindowSize,
            configuration.Headless);
    }
}